language: node_js
node_js:
- '5'

before_deploy:
- npm run build

deploy:
  provider: npm
  email: serveradmin@octoblu.com
  api_key:
    secure: ZW+PKE2r6VexRWE//7Jyi9BC6TNjO4X0fADOc1deEkz7b8b6n3JtD/d74ojx58TBo05C4z6NimUWiYCvKTVG3x9PZqJEA64mPMveAy8yFlz/3xAdb9+eccN2wDbPDcnDTR5lIZcvzgqbiIGLyxbf3q7lEQzoP3PLpeTqsh9q+OIb0MAjWH0dgiXXh7nY4XqZtKAQ09mlv2OfTdEFGXOQKKs0c9kD8jyP+wGZ/u5o9UCHzFXrrZFEEBKEYDnTR6XkcdcYoDEBeugwBk7XRC6iAi1D15TdWFAzzO6xkw61RtJF/m5MtamTCfNYg+mSFw29I187EsHGx+KnHkaFRkcE06n3xqQhrMD7SJmllPy07c+4b8NpbucGC8FdIw+psaoa2Fd70/Vli+tqM453rwQWRLlca37pROzauXcHrBQG6pfs/H91k4e8OoG3tAyt7UYQQflIpV4O4Tsmk1pxH8uoL4wv708+v4rFs1Y8K6NzEOGBEiemB0d/Xjqi0udSymQWrAyh+w/1ZU61KunEmuG/7ymt23BGA3BVfnJCLHipQdx0v9lCnYK+ih1B/KnlMnFIIPArrUQtoB4EmQ0ZYqW9ZO0qKxG2FSMnjgCiMRzCofE0QaP17M9j/vL71FxRW97HYv8kq9XptqHtp9S3vLS0li4wQpKEBkSIdJFN1c5tYNA=
  on:
    tags: true
branches:
  only:
  - "/^v[0-9]/"
after_success:
- npm run coverage
- npm run mocha:json
- bash <(curl -s https://codecov.io/bash)
- bash <(curl -s https://codecov.octoblu.com/bash)
